name: Julia CI

on:
  push:
    branches:
      - main  # Run the tests on push to the 'main' branch
  pull_request:
    branches:
      - main  # Run the tests on pull requests to the 'main' branch
  # Optionally, you can set it to run on other branches or tag pushes

jobs:
  test:
    runs-on: ubuntu-latest  # The virtual environment to run your tests in

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # This checks out your repository code
      
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1  # This action sets up Julia on the runner
        with:
          version: '1.10'  # You can specify the version of Julia you want to use

      - name: Install dependencies
        run: |
          julia -e 'using Pkg; Pkg.add("Test")'  # Install Test.jl for running tests
          julia -e 'using Pkg; Pkg.add(PackageSpec(path=joinpath(Pkg.Types.Context().current_project, "..", "SpheriCo.jl")))'  # Add SpheriCo package from local path
          julia -e 'using Pkg; Pkg.instantiate()'  # Ensure all dependencies are installed
    
      - name: Run tests
        run: |
          julia -e 'using Test; include("./tests/runtests.jl")'  # Runs the tests in 'runtests.jl'
